# Account API

# 목록
GET {{host}}/accounts?size=10
Accept: application/json


###

# 목록 With CountQuery
GET {{host}}/accounts/with-count?size=10
Accept: application/json

###

# 단건
GET {{host}}/accounts/1
Accept: application/json

###

# 이름 검색
GET {{host}}/accounts/search?name=ncucu
Accept: application/json

###

# 현재 시간 이전 기준
GET {{host}}/accounts/created-at-before
Accept: application/json

###

# 등록
POST {{host}}/accounts
Content-Type: application/json

{
  "name": "ncucu"
}

###

# 수정
PUT {{host}}/accounts/1
Content-Type: application/json

{
  "name": "ncucu2"
}

###

# 삭제
DELETE {{host}}/accounts/1
